In [ ]:
# ENGR 2300 Applied Linear Algebra
# Chapter 3.1 The Determinant of a Matrix - Notes
# Crystal J. Hollis 2/27/2025

Chapter 3.1: The Determinant of a Matrix - Notes

**Source:**
Dweik, B. (2025). Applied Linear Algebra: Determinants [Lecture]. ENGR 2300 - Applied Linear Algebra, Dallas College.
Larson, R. (2017). *Elementary Linear Algebra* (8th ed.). Cengage Learning.

---

## Chapter 3.1 Video Resources
- Textbook: https://www.larsonlinearalgebra.com/ela8e/content/instructional-videos/chapter-3/section-1/
- Gilbert Eyabi:
    - Determinants: https://www.youtube.com/watch?v=9ftZ6Efchvc&ab_channel=GilbertEyabi
    - Determinant and Elementary Operations: https://www.youtube.com/watch?v=TVcLHoHKa1M&ab_channel=GilbertEyabi
    - Properties of Determinants: https://www.youtube.com/watch?v=cSkXkDDZxuo&ab_channel=GilbertEyabi
- Trefor Bazett:
    - Determinants - a "quick" computation to tell if a matrix is invertible: https://www.youtube.com/watch?v=FMqV8GZFqzQ&ab_channel=Dr.TreforBazett
    - Determinants can be computed along any row or column - choose the easiest! : https://www.youtube.com/watch?v=-vZPtT1PVX8&ab_channel=Dr.TreforBazett

---

## Chapter 3.1 Objectives
- Find the determinant of a 2 x 2 matrix.
- Find the minors and cofactors of a matrix.
- Use expansion by cofactors to find the determinant of a matrix.
- Find the determinant of a triangular matrix.

---


# 1️⃣ The Determinant of a 2 x 2 Matrix

![Determinants Definition](img/3.1.1.png "Determinants Definition Notes")

### Definition
For a 2x2 matrix:

\begin{aligned}
A =
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
\end{aligned}

The determinant is:

\begin{aligned}
\det(A) = ad - bc
\end{aligned}

---

### 📚 Lecture Notes
- Determinants help classify matrices into **singular** and **non-singular**.
- **Singular Matrix**: Determinant = 0 (|A| = 0)
- **Non-Singular Matrix**: Determinant ≠ 0 (|A| ≠ 0)

- If a matrix is singular, it does not have an inverse.
- In systems like \(Ax = b\), a singular matrix indicates:
    - Either infinite solutions or no solution.

---
## 📌 Manual Example

![Determinants Example](img/3.1.3.png "Determinants Example")

---

## 📌 TI-84 Example: Determinant of a 2x2 Matrix

### Matrix Entry Process on TI-84
1. Press `2nd` then `Matrix` (above the `x^-1` button).
2. Move to the **EDIT** tab.
3. Select matrix `[A]` and press `ENTER`.
4. Set size to `2x2`.
5. Enter the matrix:
\begin{aligned}
A =
\begin{bmatrix}
3 & 5 \\
1 & 2
\end{bmatrix}
\end{aligned}

### Determinant Calculation Process
1. Exit to home screen: `2nd` + `MODE` (QUIT).
2. Press `2nd` + `Matrix`.
3. Move to the **MATH** tab.
4. Select **`det(`** (usually option 1).
5. Press `2nd` + `Matrix` to select `[A]`, close parenthesis.
6. Press `ENTER`.

### Result
The screen will show:

<img src="./img/3.1.10.png" alt="TI-84 Calculator" width="300"/>

---

## 📌 Python Code Cell: 2x2 Determinant Example

In [5]:
import numpy as np

A = np.array([
    [3, 5],
    [1, 2]
])

det_A = np.linalg.det(A)

print(f"Determinant of A: {det_A:.2f}")
# Final output: Determinant of A: 1.00

Determinant of A: 1.00


### Explanation
- `import numpy as np` imports the numpy library for numerical computing, giving it a nickname "np".
- `np.array()` creates a matrix-- known as a NumPy array-- from a list of lists. Each inner list represents a row of the matrix.
-  `np.linalg` is the linear algebra module inside of numpy.
- `np.linalg.det()` computes the determinant of the matrix.
- `print(f"Determinant of A: {det_A:.2f}")` is the formatted string literal, a clean way to insert variables directly into text. `det_A` is inserted into the string where `{det_A:.2f}` appears.
- `:.2f` formats `det_A` to 2 decimal places. Useful for floating point numbers.

---

## 📌 MATLAB Code Example: 2x2 Determinant Example
```Matlab
% MATLAB Code - Determinant of 2x2 Matrix
A = [3, 5;
     1, 2];

det_A = det(A);
disp(['Determinant of A: ', num2str(det_A)]);
% Output: Determinant of A: 1
```
### Explanation
- `A` defines a 2x2 matrix.
- `det()` is MATLAB’s built-in function to compute the determinant.
- `disp()` displays the result, converting the determinant to a string using `num2str()`.

![Determinants in MATLAB](img/3.1.2.png "Determinants Script in MATLAB")

---


#  2️⃣ Minors and Cofactors

### Definitions
- **Minor** $M_{ij}$: Determinant of the matrix formed by deleting row $i$ and column $j$.
- **Cofactor** $C_{ij}$: Defined as:
$$
C_{ij} = (-1)^{i+j} M_{ij}
$$

---

### 📚 Lecture Notes
- Example matrix used in lecture:
\begin{aligned}
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\end{aligned}

![Example matrix used in lecture](img/3.1.4.png "Example matrix used in lecture")

- To compute the determinant using cofactors (expanding across Row 1):
\begin{aligned}
|A| = 1 \cdot \text{Cof}(1) + 2 \cdot \text{Cof}(2) + 3 \cdot \text{Cof}(3)
\end{aligned}
- Example Cofactor Calculations:
    - \(Cof(1)\): Delete row 1, column 1, compute determinant (it is even so it is positive):

![Example matrix used in lecture](img/3.1.5.png "Example matrix used in lecture")

\begin{aligned}
\begin{bmatrix}
5 & 6 \\
8 & 9
\end{bmatrix}
\end{aligned}
\begin{aligned}
5 \cdot 9 - 8 \cdot 6 = 45 - 48 = -3
\end{aligned}
    - \(Cof(2)\): Delete row 1, column 2 (it is odd so it is negative):

![Example matrix used in lecture](img/3.1.6.png "Example matrix used in lecture")

\begin{aligned}
\begin{bmatrix}
4 & 6 \\
7 & 9
\end{bmatrix}
\end{aligned}
\begin{aligned}
-( 4 \cdot 9 - 7 \cdot 6 ) = - (36 - 42) = -(-6) \implies Cof(2) = +6
\end{aligned}
   - \(Cof(3)\): Delete row 1, column 3 (It is even so it is positive):

![Example matrix used in lecture](img/3.1.7.png "Example matrix used in lecture")

\begin{aligned}
\begin{bmatrix}
4 & 5 \\
7 & 8
\end{bmatrix}
\end{aligned}
\begin{aligned}
4 \cdot 8 - 7 \cdot 5 = 32 - 35 = -3
\end{aligned}
- Determinant:
\begin{aligned}
|A| = 1(-3) + 4(6) + 7(-3) = -3 + 24 - 21 = 0
\end{aligned}
- Since \(det(A) = 0\), matrix A is **singular**.

![Reminder](img/3.1.13.png "Reminder")

---

## 📌 TI-84 Example: Minors and Cofactors (Manual Work)

### Matrix Entry Process
1. Press `2nd` + `Matrix`.
2. Edit matrix `[A]` to size `3x3`.
3. Enter:
\begin{aligned}
A =
\begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9
\end{bmatrix}
\end{aligned}


### Manual Minor Calculation (with TI-84)
For Minor \(M_{11}\), delete row 1 and column 1.
Manually enter this minor matrix into `[B]`:
\begin{aligned}
\begin{bmatrix}
5 & 8 \\
6 & 9
\end{bmatrix}
\end{aligned}
1. Enter `[B]` (size 2x2).
2. Use `det([B])` to calculate:

<img src="./img/3.1.11.png" alt="TI-84 Calculator" width="300"/>

### Cofactor Calculation
- TI-84 does not have a built-in cofactor function, so you compute minor and manually apply sign.

### Tip
- TI-84 is not ideal for full cofactor expansion but useful for verifying **individual minors**.
- Good fallback if MATLAB or Python are unavailable.

---

## 📌 Python Code Cell: Minors and Cofactors (Manual Work)

In [8]:
import numpy as np

# Define the matrix
A = np.array([
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]
])

# Function to compute the minor matrix (delete row i and column j)
def compute_minor(matrix, row, col):
    minor = np.delete(matrix, row, axis=0)
    minor = np.delete(minor, col, axis=1)
    return minor

# Example: Compute Minor M11 (delete row 1, col 1)
minor_11 = compute_minor(A, 0, 0)

# Compute the determinant of Minor M11
det_minor_11 = np.linalg.det(minor_11)

# Compute Cofactor C11 (no sign change needed for (1,1))
cofactor_11 = det_minor_11

print("Matrix A:")
print(A)

print("\nMinor M11:")
print(minor_11)

print(f"\nDeterminant of Minor M11: {det_minor_11:.2f}")
print(f"Cofactor C11: {cofactor_11:.2f}")

# Final Output:
# Matrix A:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]

# Minor M11:
# [[5 8]
#  [6 9]]

# Determinant of Minor M11: -3.00
# Cofactor C11: -3.00


Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Minor M11:
[[5 8]
 [6 9]]

Determinant of Minor M11: -3.00
Cofactor C11: -3.00


### Explanation
- `np.delete()` Deletes row and column to create minor matrix.
- `np.linalg.det()` Computes determinant of the minor matrix.

---

## 📌 MATLAB Code Example: Minors and Cofactors for 3x3 Matrix
```Matlab
% MATLAB Code - Minors and Cofactors (3x3 Matrix)

% Define the matrix
A = [
    1, 4, 7;
    2, 5, 8;
    3, 6, 9
];

% Compute Minor M11 (delete row 1, col 1)
minor_11 = A;
minor_11(1,:) = []; % Remove 1st row
minor_11(:,1) = []; % Remove 1st column

% Compute the determinant of Minor M11
det_minor_11 = det(minor_11);

% Compute Cofactor C11 (no sign change needed for (1,1))
cofactor_11 = det_minor_11;

% Display Results
disp('Matrix A:');
disp(A);

disp('Minor M11:');
disp(minor_11);

disp(['Determinant of Minor M11: ', num2str(det_minor_11)]);
disp(['Cofactor C11: ', num2str(cofactor_11)]);

```
### Explanation
- `A = [...]` Defines matrix A.
- `A(row,:) = []` Deletes a row (removing row 1 for Minor M11).
- `A(:,col) = []` Deletes a column (removing column 1 for Minor M11).

![Determinants in MATLAB](img/3.1.12.png "Determinants Script in MATLAB")

---

# 3️⃣ Determinant using Cofactor Expansion

### Definition
For an $n \times n$ matrix $A$, the determinant can be computed by expanding along any row (typically the first row):

$$
\det(A) = \sum_{j=1}^n a_{1j} C_{1j}
$$

---

### 📚 Lecture Notes
- You can expand across any row or column, not just the first.
- Dweik recommends choosing rows/columns with the most zeros to simplify calculations.
- Example (from lecture):

$$
A =
\begin{bmatrix}
2 & -1 & 8 \\
1 & 0 & 0 \\
3 & -5 & 0
\end{bmatrix}
$$

Expanding along the second column reduces work because two entries are zero:

$$
|A| = (-1) \cdot \text{Cof}(2) = (-1) \cdot
\begin{vmatrix}
1 & 0 \\
3 & 0
\end{vmatrix}
= (-1) \cdot (1 \cdot 0 - 0 \cdot 3) = 0
$$


## 📌 TI-84 Example: Determinant using Cofactor Expansion

### Matrix Entry Process
1. Press `2nd` + `Matrix`.
2. Edit matrix `[A]` to size `3x3`.
3. Enter:
\begin{align}
A =
\begin{bmatrix}
2 & -1 & 8 \\
1 & 0 & 0 \\
3 & -5 & 0
\end{bmatrix}
\end{align}

### Cofactor Expansion along Column 2
You’ll compute:
$$
\det(A) = (-1) \cdot \text{det}(M_{12})
$$
Where $M_{12}$ is the minor formed by deleting row 1 and column 2:

\begin{align}
M_{12} =
\begin{bmatrix}
1 & 0 \\
3 & 0
\end{bmatrix}
\end{align}
1. Enter minor matrix into `[B]` (size 2x2).
2. Compute `det([B])` using `det(`.

### Apply Cofactor Sign
Since this is entry (1,2), the cofactor sign is:
$$
(-1)^{1+2} = -1
$$

Final Calculation:
$$
\det(A) = (-1) \cdot \det(B) = (-1) \cdot (1 \cdot 0 - 0 \cdot 3) = 0
$$

### Summary
- TI-84 helps compute each **minor determinant**.
- You apply the alternating sign manually.
- This method is slower than Python/MATLAB but useful if no computer is allowed.

---

## 📌 Python Code Cell: Cofactor Expansion (Manual Computation)

In [6]:
import numpy as np

A = np.array([
    [2, -1, 8],
    [1, 0, 0],
    [3, -5, 0]
])

def minor(matrix, row, col):
    sub_matrix = np.delete(matrix, row, axis=0)  # delete selected row
    sub_matrix = np.delete(sub_matrix, col, axis=1)  # delete selected column
    return np.linalg.det(sub_matrix)

# Expand along 2nd column (Column 1 in zero-indexing)
det_A = 0
for i in range(3):  # For each row
    cofactor = (-1)**(i + 1) * minor(A, i, 1)
    det_A += A[i, 1] * cofactor  # 2nd column means col=1

print(f"Determinant using Cofactor Expansion along column 2: {det_A:.2f}")
# Final Output: Determinant using Cofactor Expansion along column 2: -40.00


Determinant using Cofactor Expansion along column 2: -40.00


### Explanation
- `A = np.array([...])` Defines a 3x3 matrix.
- `minor()` Function that computes the determinant of the matrix after removing one row and column.
-  `np.delete()` Removes the specified row and column (expansion step).
- `np.linalg.det()` Finds determinant of the reduced matrix (minor).
- `for i in range(3)` Loop through each row of the column being expanded.
- `(-1)**(i+1)`  Alternating sign based on row index (cofactor sign rule).

---


## 📌 MATLAB Code Example: Cofactor Expansion (Manual Computation)
```Matlab
% MATLAB Code - Cofactor Expansion (Column 2)

A = [2, -1, 8;
     1,  0, 0;
     3, -5, 0];

det_A = 0; % Initialize determinant

for i = 1:3  % Loop over each row
    minorMatrix = A;
    minorMatrix(i, :) = []; % Delete row i
    minorMatrix(:, 2) = []; % Delete column 2 (expanding along col 2)

    minorDet = det(minorMatrix); % Find minor's determinant
    cofactor = (-1)^(i+2) * minorDet; % Apply cofactor sign rule

    det_A = det_A + A(i,2) * cofactor; % Add cofactor contribution
end

disp(['Determinant using Cofactor Expansion along column 2: ', num2str(det_A)]);
```

### Explanation
- `A = [...]` Defines a 3x3 matrix directly.
- `det_A = 0` Starts the determinant sum at zero.
-  `for i = 1:3` Loops over each row of column 2.
- `minorMatrix(i,:) = []` Deletes row i.
- `minorMatrix(:,2) = []` Deletes column 2 (expansion column).
- `det()` Finds determinant of the reduced matrix (minor).
- `(-1)^(i+2)` Cofactor sign adjustment (MATLAB uses 1-based indexing).
- `disp()` Displays result (converts number to string using `num2str()`).

![MATLAB example](img/3.1.8.png "MATLAB example")

---

# 4️⃣ Determinant of Triangular Matrices

### Definition
For a triangular matrix (upper or lower triangular), the determinant is simply the **product of the diagonal entries**.

$$
\det(A) = a_{11} a_{22} \cdots a_{nn}
$$

---

### 📚 Lecture Notes
- **Upper Triangular:** All entries **below** the diagonal are zero.
- **Lower Triangular:** All entries **above** the diagonal are zero.
- **Diagonal Matrix:** Both upper and lower triangular — only the diagonal has non-zero entries.

- Example matrix:
$$
A =
\begin{bmatrix}
2 & -1 & 0 \\
0 & 3 & 4 \\
0 & 0 & 5
\end{bmatrix}
$$

- Determinant:
$$
\det(A) = 2 \cdot 3 \cdot 5 = 30
$$

---


## 📌 TI-84 Example: Determinant of a Triangular Matrix

### Matrix Entry Process
1. Press `2nd` + `Matrix`.
2. Edit matrix `[A]` to size `3x3`.
3. Enter:
\begin{align}
A =
\begin{bmatrix}
2 & -1 & 0 \\
0 & 3 & 4 \\
0 & 0 & 5
\end{bmatrix}
\end{align}
---

### Determinant Calculation
1. Exit to home screen (`2nd` + `MODE`).
2. `2nd` + `Matrix`, select `det(`.
3. Select matrix `[A]`, close parenthesis.
4. `ENTER`.

### Result
The screen will show:

<img src="./img/3.1.14.png" alt="TI-84 Calculator" width="300"/>


### Why This Works
- The determinant of a triangular matrix is just the **product of the diagonal entries**.
- TI-84 computes directly using its built-in `det()` function, so no manual diagonal product needed.

### Quick Trick (without Matrix Mode)
If the matrix is triangular, you can also skip matrix mode and just compute: 2 × 3 × 5 = 30. This is faster when the triangular property is obvious.

---

## 📌 Python Code Cell: Triangular Matrix Determinant

In [7]:
import numpy as np

A = np.array([
    [2, -1, 0],
    [0, 3, 4],
    [0, 0, 5]
])

# Product of diagonal entries
det_A = np.prod(np.diag(A))
print(f"Determinant of triangular matrix: {det_A}")
# Final Output: Determinant of triangular matrix: 30

Determinant of triangular matrix: 30


### Explanation
- `np.diag(A)` Extracts the diagonal entries `[2, 3, 5]`.
- `np.prod()` Multiplies diagonal entries: $2 \cdot 3 \cdot 5$.

---
## 📌 MATLAB Code Example: Triangular Matrix Determinant
```Matlab
% MATLAB Code - Determinant of Triangular Matrix

A = [2, -1, 0;
     0, 3, 4;
     0, 0, 5];

% Product of diagonal entries
det_A = prod(diag(A));

disp(['Determinant of triangular matrix: ', num2str(det_A)]);
```

### Explanation
- `diag(A)` Extracts diagonal entries `[2; 3; 5]`.
- `prod()` Multiplies diagonal entries: $2 \cdot 3 \cdot 5$.
-  `disp()` Displays result, converting number to string with num2str().

![MATLAB example](img/3.1.9.png "MATLAB example")



# Summary Notes

### Key Points from Lecture
- Determinants classify matrices as:
    - Singular (|A| = 0): No inverse, system has either infinite solutions or no solution.
    - Non-Singular (|A| ≠ 0): Inverse exists, Ax = b has exactly one solution for any b.
- Determinants can be computed using:
    - Direct formula for 2x2 matrices.
    - Expansion by cofactors for larger matrices.
- Triangular Matrices: Determinant = Product of diagonal entries.
- Always choose rows/columns with most zeros to simplify cofactor expansion.

---

